/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.produto;
import services.produtoServicos;

/**
 *
 * @author 182120001
 */
public class menuCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form menuCarrinho
     */
    public menuCarrinho() {
        initComponents();
        addRowToTable();
        this.setLocationRelativeTo(null);
    }

    public void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtProdutos.getModel();
        model.getDataVector().removeAllElements();//remove todas linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[4];
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        for (produto p : proS.listaProduto()) {
            rowData[0] = p.getQuantidade();
            rowData[1] = p.getNome();
            rowData[2] = p.getPreco();
            rowData[3] = p.getIdProduto();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jbVoltar = new javax.swing.JButton();
        jbRemoverItem = new javax.swing.JButton();
        jbFinalizarCompra = new javax.swing.JButton();
        jbDesistir = new javax.swing.JButton();
        jlSHEIN = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Finalizar Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Qtd", "Nome", "Preço", "Codigo de Barras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 780, 720));

        jbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 310, -1));

        jbRemoverItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbRemoverItem.setText("Remover Item");
        jbRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverItemActionPerformed(evt);
            }
        });
        jPanel1.add(jbRemoverItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 310, -1));

        jbFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbFinalizarCompra.setText("Finalizar Compras");
        jbFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(jbFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 310, -1));

        jbDesistir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbDesistir.setText("Desistir");
        jbDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesistirActionPerformed(evt);
            }
        });
        jPanel1.add(jbDesistir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 310, -1));

        jlSHEIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlSHEIN.setForeground(new java.awt.Color(255, 255, 255));
        jlSHEIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSHEIN.setText("S H E I N");
        jPanel1.add(jlSHEIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 387, 71));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        setVisible(false);
        dispose();

        menuTenis janelaProduto = new menuTenis();
        janelaProduto.setVisible(true);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverItemActionPerformed
        int linha;
        int codigoBarras;
        linha = jtProdutos.getSelectedRow();
        codigoBarras = (int) jtProdutos.getValueAt(linha, 3);
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        Object[] resp = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(this, "Deseja realmente remover este produto da lista?", "Remove Produto", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, resp, resp[0]);
        if (resposta == 0) {
            proS.deletaProduto(Integer.toString(codigoBarras));
            JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
            addRowToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Cancelada a opção de remover produto!!");
            addRowToTable();
        }
    }//GEN-LAST:event_jbRemoverItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarCompraActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        proS.calcularValorTotalProduto();
        JOptionPane.showMessageDialog(null, "O valor total dos produtos é: R$ " + proS.calcularValorTotalProduto());
        try {
            proS.deletaTODOSprodutos();
        } catch (Exception ex) {

        }
        this.dispose();
    }//GEN-LAST:event_jbFinalizarCompraActionPerformed

    private void jbDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesistirActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        try {
            proS.deletaTODOSprodutos();
        } catch (Exception ex) {

        }
        this.dispose();
    }//GEN-LAST:event_jbDesistirActionPerformed

    private void jtProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutosMouseClicked

    }//GEN-LAST:event_jtProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCarrinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCarrinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCarrinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCarrinho.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDesistir;
    private javax.swing.JButton jbFinalizarCompra;
    private javax.swing.JButton jbRemoverItem;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlSHEIN;
    private javax.swing.JTable jtProdutos;
    // End of variables declaration//GEN-END:variables
}
