/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.produto;
import services.produtoServicos;

/**
 *
 * @author Ricardo Henrique
 */
public class menuCamiseta extends javax.swing.JFrame {

    /**
     * Creates new form menuCamiseta
     */
    public menuCamiseta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlSHEIN = new javax.swing.JLabel();
        jbCamiseta1 = new javax.swing.JButton();
        jbCamiseta = new javax.swing.JButton();
        jbCalça = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jbSetasProsseguir = new javax.swing.JButton();
        jbCamisetaBranca = new javax.swing.JButton();
        jbCamisetaVermelha = new javax.swing.JButton();
        jlNome7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlNome10 = new javax.swing.JLabel();
        jlNome4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlNome5 = new javax.swing.JLabel();
        jlNome13 = new javax.swing.JLabel();
        jlNome8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlNome6 = new javax.swing.JLabel();
        jlNome17 = new javax.swing.JLabel();
        jbCamisetaUrso = new javax.swing.JButton();
        jlNome12 = new javax.swing.JLabel();
        jbCamisetaSorriso = new javax.swing.JButton();
        jbCamisetaCreme = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlNome9 = new javax.swing.JLabel();
        jlNome11 = new javax.swing.JLabel();
        jlNome16 = new javax.swing.JLabel();
        jbCamisetaBrasil = new javax.swing.JButton();
        jlNome14 = new javax.swing.JLabel();
        jbCamisetaBrancaPreta = new javax.swing.JButton();
        jlNome15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlNome18 = new javax.swing.JLabel();
        jlNome19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jbCamisetaAzul1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSHEIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlSHEIN.setForeground(new java.awt.Color(255, 255, 255));
        jlSHEIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSHEIN.setText("S H E I N");
        jPanel1.add(jlSHEIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 387, 71));

        jbCamiseta1.setBackground(new java.awt.Color(128, 128, 128));
        jbCamiseta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCamiseta1.setForeground(new java.awt.Color(255, 255, 255));
        jbCamiseta1.setText("Tenis");
        jbCamiseta1.setBorder(null);
        jbCamiseta1.setBorderPainted(false);
        jbCamiseta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamiseta1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamiseta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 40, -1));

        jbCamiseta.setBackground(new java.awt.Color(61, 61, 61));
        jbCamiseta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCamiseta.setForeground(new java.awt.Color(255, 255, 255));
        jbCamiseta.setText("Camiseta");
        jbCamiseta.setBorder(null);
        jbCamiseta.setBorderPainted(false);
        jPanel1.add(jbCamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jbCalça.setBackground(new java.awt.Color(128, 128, 128));
        jbCalça.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCalça.setForeground(new java.awt.Color(255, 255, 255));
        jbCalça.setText("Calça");
        jbCalça.setBorder(null);
        jbCalça.setBorderPainted(false);
        jbCalça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalçaActionPerformed(evt);
            }
        });
        jPanel1.add(jbCalça, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/selecaoCategoria.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 40));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTabelaCategorias.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 640));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anuncio2.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jbSetasProsseguir.setBackground(new java.awt.Color(51, 51, 51));
        jbSetasProsseguir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbSetasProsseguir.setForeground(new java.awt.Color(255, 255, 255));
        jbSetasProsseguir.setText(">>>>>>>>>>>>>");
        jbSetasProsseguir.setBorder(null);
        jbSetasProsseguir.setBorderPainted(false);
        jbSetasProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetasProsseguirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSetasProsseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, -1, -1));

        jbCamisetaBranca.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaBranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaBranca.setBorder(null);
        jbCamisetaBranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaBrancaActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaBranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 420, -1, -1));

        jbCamisetaVermelha.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaVermelha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaVermelha.setBorder(null);
        jbCamisetaVermelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaVermelhaActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaVermelha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, -1, -1));

        jlNome7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome7.setForeground(new java.awt.Color(255, 255, 255));
        jlNome7.setText("Camiseta Branca e Preta");
        jPanel1.add(jlNome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 150, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, -1, -1));

        jlNome10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome10.setForeground(new java.awt.Color(255, 255, 255));
        jlNome10.setText("R$ 45,90");
        jPanel1.add(jlNome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 70, -1));

        jlNome4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome4.setForeground(new java.awt.Color(255, 255, 255));
        jlNome4.setText("Camiseta Sorriso");
        jPanel1.add(jlNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 110, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jlNome5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome5.setForeground(new java.awt.Color(255, 255, 255));
        jlNome5.setText("R$ 75,29");
        jPanel1.add(jlNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, 60, -1));

        jlNome13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome13.setForeground(new java.awt.Color(255, 255, 255));
        jlNome13.setText("R$ 100,00");
        jPanel1.add(jlNome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 60, -1));

        jlNome8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome8.setForeground(new java.awt.Color(255, 255, 255));
        jlNome8.setText("R$ 70,70");
        jPanel1.add(jlNome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 80, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, -1, -1));

        jlNome6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome6.setForeground(new java.awt.Color(255, 255, 255));
        jlNome6.setText("Camiseta Urso");
        jPanel1.add(jlNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 90, -1));

        jlNome17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome17.setForeground(new java.awt.Color(255, 255, 255));
        jlNome17.setText("R$ 30,00");
        jPanel1.add(jlNome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, 60, -1));

        jbCamisetaUrso.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaUrso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaUrso.setBorder(null);
        jbCamisetaUrso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaUrsoActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaUrso, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, -1, -1));

        jlNome12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome12.setForeground(new java.awt.Color(255, 255, 255));
        jlNome12.setText("Camiseta Brasil");
        jPanel1.add(jlNome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, 100, -1));

        jbCamisetaSorriso.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaSorriso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaSorriso.setBorder(null);
        jbCamisetaSorriso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaSorrisoActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaSorriso, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jbCamisetaCreme.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaCreme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaCreme.setBorder(null);
        jbCamisetaCreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaCremeActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaCreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, -1, -1));

        jlNome9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome9.setForeground(new java.awt.Color(255, 255, 255));
        jlNome9.setText("R$ 90,00");
        jPanel1.add(jlNome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 60, -1));

        jlNome11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome11.setForeground(new java.awt.Color(255, 255, 255));
        jlNome11.setText("Camiseta Creme");
        jPanel1.add(jlNome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 110, -1));

        jlNome16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome16.setForeground(new java.awt.Color(255, 255, 255));
        jlNome16.setText("Camiseta Branca");
        jPanel1.add(jlNome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 440, 100, -1));

        jbCamisetaBrasil.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaBrasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaBrasil.setBorder(null);
        jbCamisetaBrasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaBrasilActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaBrasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, -1, -1));

        jlNome14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome14.setForeground(new java.awt.Color(255, 255, 255));
        jlNome14.setText("Camiseta Vermelha");
        jPanel1.add(jlNome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, 120, -1));

        jbCamisetaBrancaPreta.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaBrancaPreta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaBrancaPreta.setBorder(null);
        jbCamisetaBrancaPreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaBrancaPretaActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaBrancaPreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, -1, -1));

        jlNome15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome15.setForeground(new java.awt.Color(255, 255, 255));
        jlNome15.setText("R$ 80,99");
        jPanel1.add(jlNome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, 70, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jlNome18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome18.setForeground(new java.awt.Color(255, 255, 255));
        jlNome18.setText("Camiseta Azul");
        jPanel1.add(jlNome18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 120, -1));

        jlNome19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome19.setForeground(new java.awt.Color(255, 255, 255));
        jlNome19.setText("R$ 57,10");
        jPanel1.add(jlNome19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 70, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaSorriso.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaAzul.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaUrso.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisaBranca.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaBrancaPreta.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaCreme.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, 130));

        jbCamisetaAzul1.setBackground(new java.awt.Color(51, 51, 51));
        jbCamisetaAzul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCamisetaAzul1.setBorder(null);
        jbCamisetaAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaAzul1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamisetaAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaBrasil.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, 150));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camisetaVermelha.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 500, 120, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSetasProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetasProsseguirActionPerformed
        setVisible(false);
        dispose();

        menuCarrinho janelaCarrinho = new menuCarrinho();
        janelaCarrinho.setVisible(true);
    }//GEN-LAST:event_jbSetasProsseguirActionPerformed

    private void jbCalçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalçaActionPerformed
        setVisible(false);
        dispose();
        
        menuCalca janelCalca = new menuCalca();
        janelCalca.setVisible(true);
    }//GEN-LAST:event_jbCalçaActionPerformed

    private void jbCamiseta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamiseta1ActionPerformed
        setVisible(false);
        dispose();
        
        menuTenis janelaTenis = new menuTenis();
        janelaTenis.setVisible(true);
    }//GEN-LAST:event_jbCamiseta1ActionPerformed

    private void jbCamisetaBrasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaBrasilActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Brasil", 1, (float) 100.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaBrasilActionPerformed

    private void jbCamisetaCremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaCremeActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Creme", 1, (float) 45.90, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaCremeActionPerformed

    private void jbCamisetaBrancaPretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaBrancaPretaActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Branca e Preta", 1, (float) 75.29, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaBrancaPretaActionPerformed

    private void jbCamisetaUrsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaUrsoActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Urso", 1, (float) 90.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaUrsoActionPerformed

    private void jbCamisetaBrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaBrancaActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Branca", 1, (float) 80.99, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaBrancaActionPerformed

    private void jbCamisetaVermelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaVermelhaActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Vermelha", 1, (float) 30.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaVermelhaActionPerformed

    private void jbCamisetaSorrisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaSorrisoActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Camiseta Sorriso", 1, (float) 70.70, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCamisetaSorrisoActionPerformed

    private void jbCamisetaAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaAzul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCamisetaAzul1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCamiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCamiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCamiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCamiseta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCamiseta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCalça;
    private javax.swing.JButton jbCamiseta;
    private javax.swing.JButton jbCamiseta1;
    private javax.swing.JButton jbCamisetaAzul1;
    private javax.swing.JButton jbCamisetaBranca;
    private javax.swing.JButton jbCamisetaBrancaPreta;
    private javax.swing.JButton jbCamisetaBrasil;
    private javax.swing.JButton jbCamisetaCreme;
    private javax.swing.JButton jbCamisetaSorriso;
    private javax.swing.JButton jbCamisetaUrso;
    private javax.swing.JButton jbCamisetaVermelha;
    private javax.swing.JButton jbSetasProsseguir;
    private javax.swing.JLabel jlNome10;
    private javax.swing.JLabel jlNome11;
    private javax.swing.JLabel jlNome12;
    private javax.swing.JLabel jlNome13;
    private javax.swing.JLabel jlNome14;
    private javax.swing.JLabel jlNome15;
    private javax.swing.JLabel jlNome16;
    private javax.swing.JLabel jlNome17;
    private javax.swing.JLabel jlNome18;
    private javax.swing.JLabel jlNome19;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel jlNome7;
    private javax.swing.JLabel jlNome8;
    private javax.swing.JLabel jlNome9;
    private javax.swing.JLabel jlSHEIN;
    // End of variables declaration//GEN-END:variables
}
