/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.produto;
import services.produtoServicos;

/**
 *
 * @author Ricardo Henrique
 */
public class menuCalca extends javax.swing.JFrame {

    /**
     * Creates new form menuCalça
     */
    public menuCalca() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCalça = new javax.swing.JButton();
        jlSHEIN = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbCamiseta1 = new javax.swing.JButton();
        jbSetasProsseguir = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlSHEIN1 = new javax.swing.JLabel();
        jbCamiseta = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbSetasProsseguir1 = new javax.swing.JButton();
        jbCalcaBranca = new javax.swing.JButton();
        jbCalcaMoletom = new javax.swing.JButton();
        jlNome7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlNome10 = new javax.swing.JLabel();
        jlNome4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlNome5 = new javax.swing.JLabel();
        jlNome13 = new javax.swing.JLabel();
        jlNome8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlNome6 = new javax.swing.JLabel();
        jlNome17 = new javax.swing.JLabel();
        jbCalcaBege = new javax.swing.JButton();
        jlNome12 = new javax.swing.JLabel();
        jbCalcaCargo = new javax.swing.JButton();
        jbCalcaFerrari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlNome9 = new javax.swing.JLabel();
        jlNome11 = new javax.swing.JLabel();
        jlNome16 = new javax.swing.JLabel();
        jbCalcaPantano = new javax.swing.JButton();
        jlNome14 = new javax.swing.JLabel();
        jbCalcaAzul = new javax.swing.JButton();
        jlNome15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlNome18 = new javax.swing.JLabel();
        jlNome19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jb3CalcasJeans1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCalça.setBackground(new java.awt.Color(62, 62, 62));
        jbCalça.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCalça.setForeground(new java.awt.Color(255, 255, 255));
        jbCalça.setText("Calça");
        jbCalça.setBorder(null);
        jbCalça.setBorderPainted(false);
        jPanel1.add(jbCalça, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, -1, -1));

        jlSHEIN.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlSHEIN.setForeground(new java.awt.Color(255, 255, 255));
        jlSHEIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSHEIN.setText("S H E I N");
        jPanel1.add(jlSHEIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 387, 71));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/selecaoCategoria.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, 40));

        jbCamiseta1.setBackground(new java.awt.Color(128, 128, 128));
        jbCamiseta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCamiseta1.setForeground(new java.awt.Color(255, 255, 255));
        jbCamiseta1.setText("Tenis");
        jbCamiseta1.setBorder(null);
        jbCamiseta1.setBorderPainted(false);
        jbCamiseta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamiseta1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbCamiseta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 40, -1));

        jbSetasProsseguir.setBackground(new java.awt.Color(51, 51, 51));
        jbSetasProsseguir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbSetasProsseguir.setForeground(new java.awt.Color(255, 255, 255));
        jbSetasProsseguir.setText(">>>>>>>>>>>>>");
        jbSetasProsseguir.setBorder(null);
        jbSetasProsseguir.setBorderPainted(false);
        jbSetasProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetasProsseguirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSetasProsseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, -1, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anuncio3.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSHEIN1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jlSHEIN1.setForeground(new java.awt.Color(255, 255, 255));
        jlSHEIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSHEIN1.setText("S H E I N");
        jPanel2.add(jlSHEIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 387, 71));

        jbCamiseta.setBackground(new java.awt.Color(128, 128, 128));
        jbCamiseta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCamiseta.setForeground(new java.awt.Color(255, 255, 255));
        jbCamiseta.setText("Camiseta");
        jbCamiseta.setBorder(null);
        jbCamiseta.setBorderPainted(false);
        jbCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamisetaActionPerformed(evt);
            }
        });
        jPanel2.add(jbCamiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTabelaCategorias.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 640));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anuncio2.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jbSetasProsseguir1.setBackground(new java.awt.Color(51, 51, 51));
        jbSetasProsseguir1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbSetasProsseguir1.setForeground(new java.awt.Color(255, 255, 255));
        jbSetasProsseguir1.setText(">>>>>>>>>>>>>");
        jbSetasProsseguir1.setBorder(null);
        jbSetasProsseguir1.setBorderPainted(false);
        jbSetasProsseguir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetasProsseguir1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbSetasProsseguir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, -1, -1));

        jbCalcaBranca.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaBranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaBranca.setBorder(null);
        jbCalcaBranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaBrancaActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaBranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 420, -1, -1));

        jbCalcaMoletom.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaMoletom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaMoletom.setBorder(null);
        jbCalcaMoletom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaMoletomActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaMoletom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, -1, -1));

        jlNome7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome7.setForeground(new java.awt.Color(255, 255, 255));
        jlNome7.setText("Calça Azul");
        jPanel2.add(jlNome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 80, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, -1, -1));

        jlNome10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome10.setForeground(new java.awt.Color(255, 255, 255));
        jlNome10.setText("R$ 77,60");
        jPanel2.add(jlNome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 70, -1));

        jlNome4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome4.setForeground(new java.awt.Color(255, 255, 255));
        jlNome4.setText("Calça Cargo");
        jPanel2.add(jlNome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 120, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jlNome5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome5.setForeground(new java.awt.Color(255, 255, 255));
        jlNome5.setText("R$ 49,99");
        jPanel2.add(jlNome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, 60, -1));

        jlNome13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome13.setForeground(new java.awt.Color(255, 255, 255));
        jlNome13.setText("R$ 233,00");
        jPanel2.add(jlNome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 660, 60, -1));

        jlNome8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome8.setForeground(new java.awt.Color(255, 255, 255));
        jlNome8.setText("R$ 123,00");
        jPanel2.add(jlNome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 90, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, -1, -1));

        jlNome6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome6.setForeground(new java.awt.Color(255, 255, 255));
        jlNome6.setText("Calça Bege");
        jPanel2.add(jlNome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 80, -1));

        jlNome17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome17.setForeground(new java.awt.Color(255, 255, 255));
        jlNome17.setText("R$ 80,00");
        jPanel2.add(jlNome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, 60, -1));

        jbCalcaBege.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaBege.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaBege.setBorder(null);
        jbCalcaBege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaBegeActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaBege, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, -1, -1));

        jlNome12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome12.setForeground(new java.awt.Color(255, 255, 255));
        jlNome12.setText("Calça Pantano");
        jPanel2.add(jlNome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 640, 90, -1));

        jbCalcaCargo.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaCargo.setBorder(null);
        jbCalcaCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaCargoActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jbCalcaFerrari.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaFerrari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaFerrari.setBorder(null);
        jbCalcaFerrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaFerrariActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaFerrari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, -1, -1));

        jlNome9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome9.setForeground(new java.awt.Color(255, 255, 255));
        jlNome9.setText("R$ 900,00");
        jPanel2.add(jlNome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 60, -1));

        jlNome11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome11.setForeground(new java.awt.Color(255, 255, 255));
        jlNome11.setText("Calça Ferrari");
        jPanel2.add(jlNome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 90, -1));

        jlNome16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome16.setForeground(new java.awt.Color(255, 255, 255));
        jlNome16.setText("Calça Branca");
        jPanel2.add(jlNome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 420, 90, -1));

        jbCalcaPantano.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaPantano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaPantano.setBorder(null);
        jbCalcaPantano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaPantanoActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaPantano, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, -1, -1));

        jlNome14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome14.setForeground(new java.awt.Color(255, 255, 255));
        jlNome14.setText("Calça Moletom");
        jPanel2.add(jlNome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 640, 90, -1));

        jbCalcaAzul.setBackground(new java.awt.Color(51, 51, 51));
        jbCalcaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jbCalcaAzul.setBorder(null);
        jbCalcaAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcaAzulActionPerformed(evt);
            }
        });
        jPanel2.add(jbCalcaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, -1, -1));

        jlNome15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome15.setForeground(new java.awt.Color(255, 255, 255));
        jlNome15.setText("R$ 87,00");
        jPanel2.add(jlNome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, 70, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quadrado.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jlNome18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome18.setForeground(new java.awt.Color(255, 255, 255));
        jlNome18.setText("3 Calças Jeans");
        jPanel2.add(jlNome18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 120, -1));

        jlNome19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome19.setForeground(new java.awt.Color(255, 255, 255));
        jlNome19.setText("R$ 330,99");
        jPanel2.add(jlNome19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 90, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaCargo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calca.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaBege.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaBranca.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaAzul.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaFerrari.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jb3CalcasJeans1.setBackground(new java.awt.Color(51, 51, 51));
        jb3CalcasJeans1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/correto.png"))); // NOI18N
        jb3CalcasJeans1.setBorder(null);
        jb3CalcasJeans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3CalcasJeans1ActionPerformed(evt);
            }
        });
        jPanel2.add(jb3CalcasJeans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaPantano.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcaMoletom.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb3CalcasJeans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3CalcasJeans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb3CalcasJeans1ActionPerformed

    private void jbCalcaAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaAzulActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Azul", 1, (float) 49.99, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaAzulActionPerformed

    private void jbCalcaPantanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaPantanoActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Pantano", 1, (float) 233.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaPantanoActionPerformed

    private void jbCalcaFerrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaFerrariActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Ferrari", 1, (float) 77.60, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaFerrariActionPerformed

    private void jbCalcaCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaCargoActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Cargo", 1, (float) 123.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaCargoActionPerformed

    private void jbCalcaBegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaBegeActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Bege", 1, (float) 900.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaBegeActionPerformed

    private void jbCalcaMoletomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaMoletomActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Moletom", 1, (float) 80.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaMoletomActionPerformed

    private void jbCalcaBrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcaBrancaActionPerformed
        produtoServicos proS = services.servicosFactory.getProdutoServicos();
        produto p = new produto(WIDTH, "Calça Branca", 1, (float) 87.00, "");

        proS.adicionaProduto(p);
    }//GEN-LAST:event_jbCalcaBrancaActionPerformed

    private void jbSetasProsseguir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetasProsseguir1ActionPerformed
        setVisible(false);
        dispose();

        menuCarrinho janelaCarrinho = new menuCarrinho();
        janelaCarrinho.setVisible(true);
    }//GEN-LAST:event_jbSetasProsseguir1ActionPerformed

    private void jbSetasProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetasProsseguirActionPerformed
        setVisible(false);
        dispose();

        menuCarrinho janelaCarrinho = new menuCarrinho();
        janelaCarrinho.setVisible(true);
    }//GEN-LAST:event_jbSetasProsseguirActionPerformed

    private void jbCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamisetaActionPerformed
        setVisible(false);
        dispose();

        menuCamiseta janelaCamiseta = new menuCamiseta();
        janelaCamiseta.setVisible(true);
    }//GEN-LAST:event_jbCamisetaActionPerformed

    private void jbCamiseta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamiseta1ActionPerformed
        setVisible(false);
        dispose();

        menuTenis janelaTenis = new menuTenis();
        janelaTenis.setVisible(true);
    }//GEN-LAST:event_jbCamiseta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCalca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCalca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb3CalcasJeans1;
    private javax.swing.JButton jbCalcaAzul;
    private javax.swing.JButton jbCalcaBege;
    private javax.swing.JButton jbCalcaBranca;
    private javax.swing.JButton jbCalcaCargo;
    private javax.swing.JButton jbCalcaFerrari;
    private javax.swing.JButton jbCalcaMoletom;
    private javax.swing.JButton jbCalcaPantano;
    private javax.swing.JButton jbCalça;
    private javax.swing.JButton jbCamiseta;
    private javax.swing.JButton jbCamiseta1;
    private javax.swing.JButton jbSetasProsseguir;
    private javax.swing.JButton jbSetasProsseguir1;
    private javax.swing.JLabel jlNome10;
    private javax.swing.JLabel jlNome11;
    private javax.swing.JLabel jlNome12;
    private javax.swing.JLabel jlNome13;
    private javax.swing.JLabel jlNome14;
    private javax.swing.JLabel jlNome15;
    private javax.swing.JLabel jlNome16;
    private javax.swing.JLabel jlNome17;
    private javax.swing.JLabel jlNome18;
    private javax.swing.JLabel jlNome19;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel jlNome7;
    private javax.swing.JLabel jlNome8;
    private javax.swing.JLabel jlNome9;
    private javax.swing.JLabel jlSHEIN;
    private javax.swing.JLabel jlSHEIN1;
    // End of variables declaration//GEN-END:variables
}
